#!/usr/bin/env python3

import argparse
import sys

sys.dont_write_bytecode = True

from app.core.console import Console, Colors
from app.core.turing import TuringCore

def get_version() -> str:
    """
    Gets the current version of the application.
    
    Returns:
        str:    The current version of the application.
    """
    try:
        with open("VERSION", "r") as f:
            return f.read().strip()
    except Exception as ex:
        Console.warn(f"There was a problem opening the version file: {Colors.RED}{ex}{Colors.NATIVE}.")
        return "unknown"

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="")
    parser.add_argument("--version", required=False, action="store_true", help="Displays the current version")
    parser.add_argument("--debug", required=False, action="store_true", help="Sets the debug flag to display debugging information")
    args = parser.parse_args()
    if args.version:
        version = get_version()
        Console.raw(version)
        sys.exit(0)
    debug = args.debug
    try:
        app: TuringCore = TuringCore(debug=debug)
        app.start()
    except Exception as ex:
        Console.err(f"There was an unknown problem: {ex}")
        Console.trace()