#!/usr/bin/env python3

import argparse
import sys
import traceback

sys.dont_write_bytecode = True

from app.interfaces.cli.console import Console
from app.core.version import get_version
from app.core.turing import Turing
from app.interfaces.cli.shell import TuringShell

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="")
    parser.add_argument("--version", required=False, action="store_true", help="Displays the current version")
    parser.add_argument("--debug", required=False, action="store_true", help="Sets the debug flag to display debugging information")
    args = parser.parse_args()
    if args.version:
        version = get_version()
        print(version)
        sys.exit(0)
    debug = args.debug
    try:
        turing: Turing = Turing(debug=debug)
        shell: TuringShell = TuringShell(turing)
        shell.start()
    except Exception as e:
        Console.Write.error(f"An unknown error occurred: {e}")
        if args.debug:
            Console.Write.exception(traceback.format_exc())